name: My Firt Github Action
on: [push]
jobs:
  buil-app:
    runs-on: ubuntu-20.04
    env:
      VERCEL_ORG_ID: a5zAolhlbRJo8PFaXD9kKreU
      VERCEL_PROJECT_ID: prj_K7cbdlobKiC1EY2s94V6rwllEe67
      VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node -v
      - name: Install node_modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Deploying the Project
        run: |
          yarn deploy
      - name: Setup Finish
        run: echo "hurray!"
